### ISSUE TITLE
Monster should keep buffs/debuffs when resurrected.

### ISSUE THREAD

**Issue by IProto** [thechungster/splinterlands-simulator#18]
**Original Game:** https://splinterlands.com/?p=battle&id=sl_e224bb62b4b9dd08c5dce49e252e2579
**Simulation:** https://splintertools.io/battle?player=uwelang&battleId=sl_e224bb62b4b9dd08c5dce49e252e2579

**Game Notes:** In round 1 Bila is resurrected but dies in one hit to Sha-Vi in round 2. The hit from the Sha-Vi should have only taken the shield off.

**Description of issue:** I believe there is a bug where resurrected creatures are not having Devine Shield reapplied to them.

**Comment by thechungster** [comment]
If anyone would like a crack at this, the monsters initial state would have to be reset when it's resurrected here.
https://github.com/thechungster/splinterlands-simulator/blob/c94f2c86cf9acc233f986d826f1268158696f961/src/utils/ability_utils.ts#L156

**Comment by jperucha** [comment]
I have created a PR solving this: https://github.com/thechungster/splinterlands-simulator/pull/27

**Comment by thechungster** [comment]
The buffs/debuffs of the monster should reapply. The armor  from summoners should be kept too
https://splinterlands.com/?p=battle&id=sm_13s0dHp9WYSqQAwwlWP4

**Comment by thechungster** [comment]
Fixed in #46
