### ISSUE TITLE
Poison damage deaths from Noxious Fumes not triggering Scavenger

### ISSUE THREAD

**Issue by IProto** [thechungster/splinterlands-simulator#20]
**Simulation**: https://splintertools.io/battle?player=lubzdr&battleId=sl_5342ed8173b9a482a303d1c05211c3e3
**Replay**: https://splinterlands.com/?p=battle&id=sl_5342ed8173b9a482a303d1c05211c3e3

**Description**: It appears from the logs that it's not showing all of the creatures which are dying to poison damage and as a result scavenger is not triggering. This match is showing as a 100% to win as a result when it's likely very low if not 0%.

**Comment by thechungster** [comment]
Need to call `this.maybeDead` after each poison tick here
https://github.com/thechungster/splinterlands-simulator/blob/master/src/game.ts#L1019-L1022
