### ISSUE TITLE
Mimosa's summoner affliction is not applied as summoner pre game buff

### ISSUE THREAD

**Issue by YukiUmetsu** [thechungster/splinterlands-simulator#52]
Currently, Mimosa is gifting affliction ability to each friendly monster in the simulator. That is not true in the game. Mimosa's affliction description is this: 
"All enemy monsters receive the affliction effect at the start of the battle.
https://github.com/thechungster/splinterlands-simulator/blob/1d122cd453555b2bcc4d3986b92b600209ceedad/src/utils/ability_utils.ts#L39 
https://github.com/thechungster/splinterlands-simulator/blob/461c42e9d9b635fe15e33a7c74a26f4a92e90027/src/game.ts#L111

Affliction should be removed from SUMMONER_ABILITY_ABILITIES
https://github.com/thechungster/splinterlands-simulator/blob/1d122cd453555b2bcc4d3986b92b600209ceedad/src/utils/ability_utils.ts#L39

and should be added to SUMMONER_DEBUFF_ABILITIES
if it doesn't work, needs another way to give affliction debuff status.

https://github.com/thechungster/splinterlands-simulator/blob/1d122cd453555b2bcc4d3986b92b600209ceedad/src/utils/ability_utils.ts#L59

**Comment by thechungster** [comment]
Fixed in https://github.com/thechungster/splinterlands-simulator/commit/853901aafde0a89bbf1f2336553661f6e38d6523
