### ISSUE TITLE
Last stand should round up

### ISSUE THREAD

**Issue by IProto** [thechungster/splinterlands-simulator#60]
There was another issue (#51 ) stating last stand should round down. I believe this is an error in the support documents when compared against the actual game engine.

See my discussion with Jacekw here: https://discord.com/channels/447924793048825866/484533198458454027/986534145213743194

Here's a link to the match: https://splinterlands.com/?p=battle&id=sl_8e45560802a8bc25b3596c85fab5f3fe

**Comment by thechungster** [comment]
That seems right I remember changing it to round up because of a battle
