### ISSUE TITLE
Last stand doesn't increasing speed or melee attack

### ISSUE THREAD

**Issue by YukiUmetsu** [thechungster/splinterlands-simulator#71]
looking at the battle logs and code, it doesn't look like last stand increase melee attack and speed 
https://github.com/thechungster/splinterlands-simulator/blob/d5a87b81c96ebf6e0779256317e5f0e8030a82bc/src/game_monster.ts#L79

**Comment by thechungster** [comment]
Bug with the logs. It shows the stats without the buffs. Attack / speed buffs/debufs are calculated when they are used in getPostAbility{Stat}
