### ISSUE TITLE
Scattershot should not directly hit camouflage monster

### ISSUE THREAD

**Issue by YukiUmetsu** [thechungster/splinterlands-simulator#87]
https://splintertools.io/battle/sl_4b23f55f2010ec86b724bf0080ff640b?player=ueyuey&cards=463,152,462,119,155,421,352
<img width="435" alt="スクリーンショット 2022-09-12 午後6 09 49" src="https://user-images.githubusercontent.com/10085511/189773919-bd20a97d-fd8d-487f-8d0d-21761014bc9e.png">

**Comment by thechungster** [comment]
Fixed in 30e66140fb64d452b6a9eb282fbb9e56262ef1b9
